### ISSUE TITLE
1.Oversampling.pd

### ISSUE THREAD

**Issue by alfonso73** [porres/Live-Electornics-Tutorial#2]
First line of text a little typo. "prtials" instead of "partials".
[pd bl.saw~] sub patch is still in portuguese

should be something like
"16x Oversampling

<= Sawtooth

<= Anti-Aliasing Filter (Low-pass) *
      Cutoff frequency is 3/4 of Nyquist

* This object implements a 10th order Low Pass Butterworth filter.
Theory about filters explaining this Low Pass implementation will be presented later.
The filter order determines the amplitude decay for every octave above the cutoff frequency.
Every order determines a 6dB decay (first order decays 6dB per octave, second order decays 12dB and so on). In other words, being a 10th order filter, it decays 60dB per octave"

Maybe using "pole" instead of "order" is better in english?

**Comment by porres** [comment]
done, thanks

> Maybe using "pole" instead of "order" is better in english?

nope, they are and mean different things

**Comment by alfonso73** [comment]
perfect...i've to review filter theory :-)
